version: '3'
services:
  zookeeper:
    image: zookeeper:3.9.0
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      base-env-network:
        aliases:
          - zookeeper
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/java.env:/conf/java.env
      - ./conf/zoo.cfg:/conf/zoo.cfg
      - ./data:/data
      - ./logs:/logs


# docker network create base-env-network          
networks:
  base-env-network:
    external:
      name: "base-env-network"
    

